version: "3.9"

services:
  app:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      mysql:
        condition: service_healthy


  mysql:
    image: mysql:8.0
    container_name: mysql-digitalhouse
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: carsrentdh
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10



volumes:
  mysql-data:
